### ISSUE TITLE
Issue with mermaid sequence diagram not rendering

### ISSUE THREAD

**Issue by nandhiniarumugachamy** [kiranma72/abdm-docs#29]
Mermaid sequence diagram is not getting rendered under **Creation of ABHA Number - using Driving License**

**Comment by kiranma72** [comment]
<img width="832" alt="image" src="https://user-images.githubusercontent.com/96676798/230721810-c4e0a364-1a49-49a2-ab51-85661b05ee98.png">

Nandini, it says syntax error now. Please check

**Comment by YeshnaArya** [comment]
The issue has been resolved.
